version: '3.9'
services:
    space:
      build: space
      ports:
        - '8000:8000'
      depends_on:
        db:
          condition: service_healthy
      env_file:
        - '.space.env'
      links:
        - 'db:db'
      restart: always
    db:
      build: db
      env_file:
        - '.db.env'
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      restart: always