#!/bin/bash

MYSQL_DATABASE="space"
MYSQL_USER="space"

MYSQL_ROOT_PASSWORD=$(openssl rand -hex 32)
MYSQL_PASSWORD=$(openssl rand -hex 32)
SECRET_KEY=$(openssl rand -base64 32)

cat > .space.env << EOF
ROCKET_ADDRESS="0.0.0.0"
ROCKET_DATABASES="{app_db={url=\"mysqlx://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}\"}}"
ROCKET_TEMPLATE_DIR="templates"
ROCKET_SECRET_KEY="${SECRET_KEY}"
EOF

cat > .db.env << EOF
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
MYSQL_DATABASE="${MYSQL_DATABASE}"
MYSQL_USER="${MYSQL_USER}"
MYSQL_PASSWORD="${MYSQL_PASSWORD}"
EOF